name: YOPO Install and Run Test
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install YOPO
      run: |
        python -m pip install --upgrade pip
        pip install yopo
    - name: Running Test Code
      run: |
          from yopo import dashboard
          import pandas as pd

          df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/iris-data.csv")
          dashboard(input=df,mode="inline",port=8052, plotly_config={"template":"plotly_dark"})
